---
networks:
  ioquake3:
    external: false

services:
  ioquake3:
    build:
      context: .
    container_name: ioquake3
    restart: unless-stopped
    environment:
      - MOTD
      - RCON_PASS
      - EXTRA_ARGS
    networks:
      - ioquake3
    volumes:
      - "/mnt/Partage/Logiciels/quake/baseq3:/quake/baseq3"
      - "/mnt/Partage/Logiciels/quake/config:/config:rw"
    ports:
      - "27960/udp:27960/udp"
